@startuml Produto
class Produto {
    + nome: str
    + preco: float
    + quantidade: int
    + valorTotalEmEstoque(): float
    + adicionarProdutos(): int
    + removerProdutos(): int
}

@enduml