import pyautogui as py

py.press("Win")
py.write("chrome")
py.sleep(2)
py.press("enter")
py.sleep(2)
py.write("SENAI Americana")
py.press("enter")
py.sleep(4)
# print(py.position())
py.click(x=258, y=459, button="left")
py.sleep(2)
# print(py.position())
py.click(x=1303, y=769, button="left")
py.sleep(2)
# print(py.position())
py.click(x=222, y=503, button="left")
py.write("Python")
py.sleep(4)
py.press("enter")
py.sleep(2)
py.vscroll(-200)
# Aula 03 de Python com Frameworks